// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xexphmhszjtivmbknmzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhleHBobWhzemp0aXZtYmtubXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODMyNTYsImV4cCI6MjA2MDc1OTI1Nn0.lGXMedYW4YhDk5jgLnVz6bC2ClQV6QtiXDECPIhdUEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);